/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Cliente;

/**
 *
 * @author lucas
 */
public class ClienteVisao extends javax.swing.JFrame {

    /**
     * Creates new form ClienteVisao
     */
    public ClienteVisao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JTabbedPane();
        pAlunos = new javax.swing.JPanel();
        pProfessor = new javax.swing.JPanel();
        pDiciplinas = new javax.swing.JPanel();
        pSalas = new javax.swing.JPanel();
        pAulas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pAlunos.setLayout(new java.awt.BorderLayout());
        painelGeral.addTab("Alunos", pAlunos);

        pProfessor.setLayout(new java.awt.BorderLayout());
        painelGeral.addTab("Professor", pProfessor);

        pDiciplinas.setLayout(new java.awt.BorderLayout());
        painelGeral.addTab("Diciplinas", pDiciplinas);

        pSalas.setLayout(new java.awt.BorderLayout());
        painelGeral.addTab("Salas", pSalas);

        pAulas.setLayout(new java.awt.BorderLayout());
        painelGeral.addTab("Aulas", pAulas);

        getContentPane().add(painelGeral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteVisao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pAlunos;
    private javax.swing.JPanel pAulas;
    private javax.swing.JPanel pDiciplinas;
    private javax.swing.JPanel pProfessor;
    private javax.swing.JPanel pSalas;
    private javax.swing.JTabbedPane painelGeral;
    // End of variables declaration//GEN-END:variables
}
